export const LOGIN_CONSTRUCTION = 'LOGIN_CONSTRUCTION'
export const LOGIN_CONSTRUCTION_SUCCESS = 'LOGIN_CONSTRUCTION_SUCCESS'
export const LOGIN_CONSTRUCTION_FAIL = 'LOGIN_CONSTRUCTION_FAIL'
export const LOGOUT = 'LOGOUT'

export const ME_CONSTRUCTION = 'ME_CONSTRUCTION'
export const ME_CONSTRUCTION_SUCCESS = 'ME_CONSTRUCTION_SUCCESS'
export const ME_CONSTRUCTION_FAIL = 'ME_CONSTRUCTION_FAIL'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'

export const CHANGE_PROFILE = 'CHANGE_PROFILE'
export const CHANGE_PROFILE_SUCCESS = 'CHANGE_PROFILE_SUCCESS'
export const CHANGE_PROFILE_FAIL = 'CHANGE_PROFILE_FAIL'

export const GET_ALL_GROUP = 'GET_ALL_GROUP'
export const GET_ALL_GROUP_SUCCESS = 'GET_ALL_GROUP_SUCCESS'
export const GET_ALL_GROUP_FAIL = 'GET_ALL_GROUP_FAIL'

export const ADD_GROUP = 'ADD_GROUP'
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS'
export const ADD_GROUP_FAIL = 'ADD_GROUP_FAIL'

export const GET_GROUP_ID = 'GET_GROUP_ID'
export const GET_GROUP_ID_SUCCESS = 'GET_GROUP_ID_SUCCESS'
export const GET_GROUP_ID_FAIL = 'GET_GROUP_ID_FAIL'

export const UPDATE_GROUP = 'UPDATE_GROUP'
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
export const UPDATE_GROUP_FAIL = 'UPDATE_GROUP_FAIL'

export const DELETE_GROUP = 'DELETE_GROUP'
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL'

export const SEARCH_GROUP = 'SEARCH_GROUP'
export const SEARCH_GROUP_SUCCESS = 'SEARCH_GROUP_SUCCESS'
export const SEARCH_GROUP_FAIL = 'SEARCH_GROUP_FAIL'

export const GET_ALL_USER = 'GET_ALL_USER'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAIL = 'GET_ALL_USER_FAIL'

export const ADD_USER = 'ADD_USER'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'

export const PERMISSION = 'PERMISSION'
export const PERMISSION_SUCCESS = 'PERMISSION_SUCCESS'
export const PERMISSION_FAIL = 'PERMISSION_FAIL'

export const GET_USER_ID = 'GET_USER_ID'
export const GET_USER_ID_SUCCESS = 'GET_USER_ID_SUCCESS'
export const GET_USER_ID_FAIL = 'GET_USER_ID_FAIL'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

export const ADD_EVENT = 'ADD_EVENT'
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS'
export const ADD_EVENT_FAIL = 'ADD_EVENT_FAIL'

export const GET_ALL_EVENT = 'GET_ALL_EVENT'
export const GET_ALL_EVENT_SUCCESS = 'GET_ALL_EVENT_SUCCESS'
export const GET_ALL_EVENT_FAIL = 'GET_ALL_EVENT_FAIL'

export const GET_EVENT_BY_RANGE_DATE = 'GET_EVENT_BY_RANGE_DATE'

export const GET_EVENT_HISTORY = 'GET_EVENT_HISTORY'
export const GET_EVENT_HISTORY_SUCCESS = 'GET_EVENT_HISTORY_SUCCESS'
export const GET_EVENT_HISTORY_FAIL = 'GET_EVENT_HISTORY_FAIL'

export const UPDATE_EVENT = 'UPDATE_EVENT'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL'

export const DELETE_EVENT = 'DELETE_EVENT'
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS'
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL'

export const COMPLETE_EVENT = 'COMPLETE_EVENT'
export const COMPLETE_EVENT_SUCCESS = 'COMPLETE_EVENT_SUCCESS'
export const COMPLETE_EVENT_FAIL = 'COMPLETE_EVENT_FAIL'

export const CANCEL_EVENT = 'CANCEL_EVENT'
export const CANCEL_EVENT_SUCCESS = 'CANCEL_EVENT_SUCCESS'
export const CANCEL_EVENT_FAIL = 'CANCEL_EVENT_FAIL'

export const REOPEN_EVENT = 'REOPEN_EVENT'
export const REOPEN_EVENT_SUCCESS = 'REOPEN_EVENT_SUCCESS'
export const REOPEN_EVENT_FAIL = 'REOPEN_EVENT_FAIL'

export const SEARCH_EVENT = 'SEARCH_EVENT'
export const SEARCH_EVENT_SUCCESS = 'SEARCH_EVENT_SUCCESS'
export const SEARCH_EVENT_FAIL = 'SEARCH_EVENT_FAIL'

export const USER_BY_EVENT = 'USER_BY_EVENT'
export const USER_BY_EVENT_SUCCESS = 'USER_BY_EVENT_SUCCESS'
export const USER_BY_EVENT_FAIL = 'USER_BY_EVENT_FAIL'

export const APPROVE_USER_TO_EVENT = 'APPROVE_USER_TO_EVENT'
export const APPROVE_USER_TO_EVENT_SUCCESS = 'APPROVE_USER_TO_EVENT_SUCCESS'
export const APPROVE_USER_TO_EVENT_FAIL = 'APPROVE_USER_TO_EVENT_FAIL'

export const REMOVE_USER_FROM_EVENT = 'REMOVE_USER_FROM_EVENT'
export const REMOVE_USER_FROM_EVENT_SUCCESS = 'REMOVE_USER_FROM_EVENT_SUCCESS'
export const REMOVE_USER_FROM_EVENT_FAIL = 'REMOVE_USER_FROM_EVENT_FAIL'

export const ADD_USER_TO_EVENT = 'ADD_USER_TO_EVENT'
export const ADD_USER_TO_EVENT_SUCCESS = 'ADD_USER_TO_EVENT_SUCCESS'
export const ADD_USER_TO_EVENT_FAIL = 'ADD_USER_TO_EVENT_FAIL'

export const CANCEL_USER_REQUEST = 'CANCEL_USER_REQUEST'
export const CANCEL_USER_REQUEST_SUCCESS = 'CANCEL_USER_REQUEST_SUCCESS'
export const CANCEL_USER_REQUEST_FAIL = 'CANCEL_USER_REQUEST_FAIL'